import type { Step } from "@/types"

export const STEPS: Step[] = [
  {
    id: 1,
    act: 1,
    title: "Crystallize your idea",
    description: "Define your problem clearly before anything else.",
    xpReward: 50,
    aiOutput: "ICP + competitive advantage",
    tasks: [
      { id: "1-1", label: "Describe the problem in 1 sentence", completed: false },
      { id: "1-2", label: "Identify 5 precise target profiles", completed: false },
      { id: "1-3", label: "Find 10 online places where they hang out", completed: false },
      { id: "1-4", label: "List 5 existing solutions + their weaknesses", completed: false },
    ],
  },
  {
    id: 2,
    act: 1,
    title: "Validate before coding",
    description: "Get 10 people to say they have the problem. Find 3 ready to pay.",
    xpReward: 100,
    aiOutput: "5 posts + 30 DM templates + @handles list",
    tasks: [
      { id: "2-1", label: "Post in 5 communities (problem, not product)", completed: false },
      { id: "2-2", label: "DM 30 targeted people", completed: false },
      { id: "2-3", label: "Get 10 \"yes I have this problem\"", completed: false },
      { id: "2-4", label: "Find 3 people ready to pay", completed: false },
    ],
  },
  {
    id: 3,
    act: 1,
    title: "Landing page live",
    description: "A real URL with a waitlist. No code needed.",
    xpReward: 100,
    aiOutput: "Full landing page copy",
    tasks: [
      { id: "3-1", label: "Deploy Next.js boilerplate on Vercel", completed: false },
      { id: "3-2", label: "Generate and integrate copy with AI", completed: false },
      { id: "3-3", label: "Connect a domain", completed: false },
      { id: "3-4", label: "Set up automated waitlist (Resend)", completed: false },
    ],
  },
  {
    id: 4,
    act: 1,
    title: "100 real visitors",
    description: "Drive traffic to your landing page.",
    xpReward: 100,
    aiOutput: "10 posts + 30 personalized DMs",
    tasks: [
      { id: "4-1", label: "Post in 10 communities", completed: false },
      { id: "4-2", label: "Send 30 DMs", completed: false },
      { id: "4-3", label: "3 personal network posts", completed: false },
      { id: "4-4", label: "1 Show HN or ProductHunt Ship", completed: false },
      { id: "4-5", label: "Reach 100 unique visitors", completed: false },
    ],
  },
  {
    id: 5,
    act: 1,
    title: "Build your MVP",
    description: "1 core feature. Auth. Stripe. Deployed.",
    xpReward: 150,
    aiOutput: "Technical plan tailored to your stack",
    tasks: [
      { id: "5-1", label: "Define 1 core feature", completed: false },
      { id: "5-2", label: "Configure Supabase auth", completed: false },
      { id: "5-3", label: "Configure Stripe", completed: false },
      { id: "5-4", label: "Deploy to production", completed: false },
    ],
  },
  {
    id: 6,
    act: 1,
    title: "Convert your waitlist",
    description: "Turn waitlisters into paying customers.",
    xpReward: 150,
    aiOutput: "Email sequence + call script",
    tasks: [
      { id: "6-1", label: "Send early bird email", completed: false },
      { id: "6-2", label: "Book 3 calls with waitlisters", completed: false },
      { id: "6-3", label: "Follow up on day 3", completed: false },
      { id: "6-4", label: "Activate limited offer", completed: false },
    ],
  },
  {
    id: 7,
    act: 1,
    title: "🎉 First sale",
    description: "One Stripe payment. That's all it takes.",
    xpReward: 500,
    aiOutput: "Cinematic animation + Act 2 unlocked",
    tasks: [
      { id: "7-1", label: "First Stripe payment received", completed: false },
      { id: "7-2", label: "Send personal thank you message", completed: false },
      { id: "7-3", label: "Share publicly", completed: false },
    ],
  },
]
