import type { Step } from "@/types"

export const STEPS: Step[] = [
  // ─── ACT 1 ──────────────────────────────────────────────────────────────
  {
    id: 1,
    act: 1,
    title: "Crystallize your idea",
    description: "Define your problem clearly before anything else. No code yet.",
    xpReward: 50,
    aiOutput: "ICP + competitive advantage",
    affiliates: [],
    tasks: [
      { id: "1-1", label: "Describe the problem in 1 sentence", completed: false },
      { id: "1-2", label: "Identify 5 precise target profiles", completed: false },
      { id: "1-3", label: "Find 10 online places where they hang out", completed: false },
      { id: "1-4", label: "List 5 existing solutions + their weaknesses", completed: false },
    ],
  },
  {
    id: 2,
    act: 1,
    title: "Validate before coding",
    description: "Get 10 people to confirm the problem. Find 3 ready to pay. No product yet.",
    xpReward: 100,
    aiOutput: "5 posts + 30 DM templates + @handles list",
    affiliates: [],
    tasks: [
      { id: "2-1", label: "Post in 5 communities (problem, not product)", completed: false },
      { id: "2-2", label: "DM 30 targeted people", completed: false },
      { id: "2-3", label: 'Get 10 "yes I have this problem"', completed: false },
      { id: "2-4", label: "Find 3 people ready to pay", completed: false },
    ],
  },
  {
    id: 3,
    act: 1,
    title: "Landing page live",
    description: "A real URL with a waitlist. Generated copy. No design skills needed.",
    xpReward: 100,
    aiOutput: "Full landing page copy",
    affiliates: [
      { label: "Get a domain on Namecheap", url: "https://www.namecheap.com", note: "~$10/yr" },
      { label: "Deploy free on Vercel", url: "https://vercel.com", note: "Free tier" },
    ],
    tasks: [
      { id: "3-1", label: "Deploy Next.js boilerplate on Vercel", completed: false },
      { id: "3-2", label: "Generate and integrate copy with AI", completed: false },
      { id: "3-3", label: "Connect a domain", completed: false },
      { id: "3-4", label: "Set up automated waitlist (Resend)", completed: false },
    ],
  },
  {
    id: 4,
    act: 1,
    title: "100 real visitors",
    description: "Drive real traffic to your landing page. No ads needed.",
    xpReward: 100,
    aiOutput: "10 community posts + 30 personalized DMs",
    affiliates: [],
    tasks: [
      { id: "4-1", label: "Post in 10 communities", completed: false },
      { id: "4-2", label: "Send 30 DMs", completed: false },
      { id: "4-3", label: "3 personal network posts", completed: false },
      { id: "4-4", label: "1 Show HN or ProductHunt Ship", completed: false },
      { id: "4-5", label: "Reach 100 unique visitors", completed: false },
    ],
  },
  {
    id: 5,
    act: 1,
    title: "Build your MVP",
    description: "1 core feature. Auth. Stripe. Deployed to production.",
    xpReward: 150,
    aiOutput: "Technical plan tailored to your stack",
    affiliates: [
      { label: "Database & auth on Supabase", url: "https://supabase.com", note: "Free tier" },
      { label: "Payments on Stripe", url: "https://stripe.com", note: "No monthly fee" },
      { label: "Deploy on Railway", url: "https://railway.app", note: "$5/mo" },
    ],
    tasks: [
      { id: "5-1", label: "Define 1 core feature (scope ruthlessly)", completed: false },
      { id: "5-2", label: "Configure Supabase auth", completed: false },
      { id: "5-3", label: "Configure Stripe payments", completed: false },
      { id: "5-4", label: "Deploy to production", completed: false },
    ],
  },
  {
    id: 6,
    act: 1,
    title: "Convert your waitlist",
    description: "Turn waitlisters into paying customers with a personal email sequence.",
    xpReward: 150,
    aiOutput: "Email sequence + call script",
    affiliates: [
      { label: "Send emails with Resend", url: "https://resend.com", note: "3k emails/mo free" },
    ],
    tasks: [
      { id: "6-1", label: "Send early bird email to waitlist", completed: false },
      { id: "6-2", label: "Book 3 calls with waitlisters", completed: false },
      { id: "6-3", label: "Follow up on day 3", completed: false },
      { id: "6-4", label: "Activate limited-time offer", completed: false },
    ],
  },
  {
    id: 7,
    act: 1,
    title: "🎉 First sale",
    description: "One Stripe payment changes everything. This is the milestone.",
    xpReward: 500,
    aiOutput: "Thank you message + announcement thread",
    affiliates: [],
    tasks: [
      { id: "7-1", label: "First Stripe payment received", completed: false },
      { id: "7-2", label: "Send personal thank you to first customer", completed: false },
      { id: "7-3", label: "Share the win publicly", completed: false },
    ],
  },

  // ─── ACT 2 ──────────────────────────────────────────────────────────────
  {
    id: 8,
    act: 2,
    title: "10 paying customers",
    description: "Replicate the first sale manually. Outreach, not ads.",
    xpReward: 200,
    aiOutput: "50 personalized outreach messages + 3 customer story posts",
    affiliates: [],
    tasks: [
      { id: "8-1", label: "Contact 50 people from your validation list", completed: false },
      { id: "8-2", label: "Send personal email to every waitlister", completed: false },
      { id: "8-3", label: "Post 3 'early customer story' updates", completed: false },
      { id: "8-4", label: "Offer onboarding call to each new customer", completed: false },
      { id: "8-5", label: "Reach 10 paying customers", completed: false },
    ],
  },
  {
    id: 9,
    act: 2,
    title: "$100 MRR",
    description: "Focus on retention and structured feedback before scaling.",
    xpReward: 300,
    aiOutput: "Feedback call script + NPS survey + friction analysis",
    affiliates: [],
    tasks: [
      { id: "9-1", label: "Do a 30-min call with every paying customer", completed: false },
      { id: "9-2", label: "Identify your product's 'aha moment'", completed: false },
      { id: "9-3", label: "Fix the top 3 friction points", completed: false },
      { id: "9-4", label: "Launch a simple NPS survey", completed: false },
      { id: "9-5", label: "Reach $100 MRR", completed: false },
    ],
  },
  {
    id: 10,
    act: 2,
    title: "$500 MRR",
    description: "Find your first acquisition channel that actually scales.",
    xpReward: 400,
    aiOutput: "10 targeted content pieces + channel strategy for your ICP",
    affiliates: [],
    tasks: [
      { id: "10-1", label: "Test 3 acquisition channels", completed: false },
      { id: "10-2", label: "Publish 10 targeted content pieces", completed: false },
      { id: "10-3", label: "Track source of every new customer", completed: false },
      { id: "10-4", label: "Double down on the best-performing channel", completed: false },
      { id: "10-5", label: "Reach $500 MRR", completed: false },
    ],
  },
  {
    id: 11,
    act: 2,
    title: "$1,000 MRR",
    description: "Systemize acquisition. Reduce churn. Optimize pricing.",
    xpReward: 500,
    aiOutput: "5-email onboarding sequence + case study page + pricing recommendations",
    affiliates: [],
    tasks: [
      { id: "11-1", label: "Automate onboarding (5-day email sequence)", completed: false },
      { id: "11-2", label: "Set up churn alerts (Stripe)", completed: false },
      { id: "11-3", label: "Create 1 customer case study page", completed: false },
      { id: "11-4", label: "Add annual plan + upgrade path", completed: false },
      { id: "11-5", label: "Reach $1,000 MRR", completed: false },
    ],
  },
  {
    id: 12,
    act: 2,
    title: "$2,500 MRR",
    description: "Accelerate your main channel. Add referrals. Get your first partnership.",
    xpReward: 600,
    aiOutput: "Referral program copy + partnership pitch + landing page rewrite",
    affiliates: [],
    tasks: [
      { id: "12-1", label: "Publish 20 more pieces on your best channel", completed: false },
      { id: "12-2", label: "Launch a simple referral program", completed: false },
      { id: "12-3", label: "Get 1 newsletter mention or partnership", completed: false },
      { id: "12-4", label: "Rewrite landing with real customer language", completed: false },
      { id: "12-5", label: "Reach $2,500 MRR", completed: false },
    ],
  },
  {
    id: 13,
    act: 2,
    title: "$5,000 MRR",
    description: "Open a second acquisition channel. Automate. Start thinking about delegation.",
    xpReward: 750,
    aiOutput: "Affiliate program setup + win-back sequence + delegation plan",
    affiliates: [],
    tasks: [
      { id: "13-1", label: "Test and validate a 2nd acquisition channel", completed: false },
      { id: "13-2", label: "Launch affiliate program", completed: false },
      { id: "13-3", label: "Build a churn win-back email sequence", completed: false },
      { id: "13-4", label: "Document your processes for delegation", completed: false },
      { id: "13-5", label: "Reach $5,000 MRR", completed: false },
    ],
  },
  {
    id: 14,
    act: 2,
    title: "$10,000 MRR 👑",
    description: "Two channels running autonomously. First hire. Share the playbook.",
    xpReward: 1000,
    aiOutput: "Job description + '$10k MRR' announcement thread + financial dashboard setup",
    affiliates: [],
    tasks: [
      { id: "14-1", label: "2 acquisition channels running semi-autonomously", completed: false },
      { id: "14-2", label: "Make your first hire (support, marketing, or dev)", completed: false },
      { id: "14-3", label: "Calculate LTV, CAC, and MRR churn", completed: false },
      { id: "14-4", label: "Share your story publicly", completed: false },
      { id: "14-5", label: "Reach $10,000 MRR", completed: false },
    ],
  },
]

export function getStep(id: number) {
  return STEPS.find((s) => s.id === id)
}

export const ACT1_STEPS = STEPS.filter((s) => s.act === 1)
export const ACT2_STEPS = STEPS.filter((s) => s.act === 2)
export const TOTAL_XP = STEPS.reduce((sum, s) => sum + s.xpReward, 0)
